apiVersion: training.training.dcnlab.com/v1alpha1
kind: SpotInstanceJob
metadata:
  name: my-training-job
spec:
  replicas: 2
  instanceTemplateRef:
    name: testla-t4-1-gpu
  gcpCredentialsSecretRef:
    name: gcp-credentials
    namespace: default
  checkpointConfig:
    checkpointImageRepo: "docker.io/lehuannhatrang/gpu-checkpoints"
    checkpointInterval: "30m"
    # Optional: credentials for pushing checkpoint images
    checkpointRepoCredentialRef:
      name: "backup-registry-lehuannhatrang-docker-1762182873"
      namespace: "stateful-migration"
  jobTemplate:
    spec:
      template:
        spec:
          runtimeClassName: nvidia-cdi
          restartPolicy: Never
          containers:
          - name: trainer
            image: docker.io/deepspeed/deepspeed:latest
            command: ["/bin/bash", "-c"]
            args:
              - |
                python -m pip install --upgrade pip;
                pip install transformers==4.18.0;
                export PYTHONPATH=/home/deepspeed/.local/lib/python3.6/site-packages:$PYTHONPATH;
                deepspeed --num_gpus=1 /workspace/train.py
            resources:
              limits:
                nvidia.com/gpu: 1
            env:
              - name: OMP_NUM_THREADS
                value: "1"
              - name: PYTHONPATH
                value: "/home/deepspeed/.local/lib/python3.6/site-packages"
            volumeMounts:
              - name: workspace
                mountPath: /workspace
          volumes:
            - name: workspace
              configMap:
                name: train-script